version: '3.1'
services:
  cmdb:
    image: ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
    container_name: bk_cmdb
    hostname: BK_CMDB
    volumes:
      - ./data/mongodb:/data/sidecar/mongodb/db
      - ./data/redis:/data/sidecar/redis/db
      - ./data/zookeeper:/data/sidecar/zookeeper/data
      - ./logs/mongodb:/data/sidecar/mongodb/log
      - ./logs/redis:/data/sidecar/redis/log
      # - ./logs/zookeeper:/data/sidecar/zookeeper/log

    networks: 
      vpn:
        ipv4_address: 172.168.33.2
    ports:
      - "8090:8090"
    restart: on-failure

networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.33.0/24
          gateway: 172.168.33.1

